# Generated by Django 4.2.17 on 2025-02-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
